class StoreFriendList {
  _getData(){
    let arr =[
      {en: 'original', vi: 'nguyên bản', ipa: '/əˈrɪdʒ.ən.əl/' , type: 'adv',unit: 1},
      {en: 'culture', vi: 'văn hóa', ipa: '/ˈkʌl.tʃər/' , type: 'n',unit: 1},
      {en: 'vocabulary', vi: 'từ vựng', ipa: ' /vəˈkæb.jə.lər.i/' , type: 'n',unit: 1},
      {en: 'follow', vi: 'theo dõi', ipa: '/ˈfɒl.əʊ/' , type: 'v',unit: 1},
      {en: 'course', vi: 'khóa học', ipa: '/kɔːs/' , type: 'n',unit: 1},
      {en: 'vistor', vi: 'khách thăm quan', ipa: '/ˈvɪz.ɪ.tər/' , type: 'adv',unit: 1},
      {en: 'beginner', vi: 'người mới', ipa: '/bɪˈɡɪn.ər/' , type: 'n',unit: 1},
      {en: 'abroad', vi: 'ở nước ngoài', ipa: '/əˈbrɔːd/' , type: 'adv',unit: 1},
      {en: 'confident', vi: 'tự tin', ipa: '/ˈkɒn.fɪ.dənt/' , type: 'adj',unit: 1},
      {en: 'speaker', vi: 'người nói', ipa: '/ˈspiː.kər/' , type: 'n',unit: 1},
      {en: 'skill', vi: 'kỹ năng', ipa: '/skɪl/' , type: 'n',unit: 1},
      {en: 'scared', vi: 'sợ hãi', ipa: '/skeəd/' , type: 'adj',unit: 1},
      {en: 'progress', vi: 'tiến bộ', ipa: '/ˈprəʊ.ɡres/' , type: 'n',unit: 1},
      {en: 'difficulty', vi: 'sự khó khăn', ipa: '/ˈdɪf.ɪ.kəl.ti/' , type: 'n',unit: 1},
      {en: 'foreigner', vi: 'người nước ngoài', ipa: '/ˈfɒr.ə.nər/' , type: 'n',unit: 1},
      {en: 'communicate', vi: 'giao tiếp', ipa: '/kəˈmjuː.nɪ.keɪt/' , type: 'v',unit: 1},
      {en: 'idea', vi: 'ý tưởng', ipa: '/ʃaɪ/' , type: 'adj',unit: 1},
      {en: 'topic', vi: 'chủ đề', ipa: '/ˈtɒp.ɪk/' , type: 'n',unit: 1},
      {en: 'language', vi: 'ngôn ngữ', ipa: '/ˈlæŋ.ɡwɪdʒ/' , type: 'n',unit: 1},
      {en: 'conversation', vi: 'cuộc trò truyện', ipa: '/ˌkɒn.vəˈseɪ.ʃən/' , type: 'n',unit: 1},
      {en: 'certificate', vi: 'chứng chỉ', ipa: '/səˈtɪf.ɪ.kət/' , type: 'n',unit: 1},
      {en: 'understand', vi: 'hiểu', ipa: '/ˌʌn.dəˈstænd/' , type: 'adv',unit: 1},
      {en: 'follow one dream', vi: 'theo đuổi ước mơ của bản thân', ipa: '' , type: 'cum',unit: 1},
      {en: 'take an english course', vi: 'tham gia khóa học tiếng anh', ipa: '' , type: 'cum',unit: 1},
      {en: 'learn new things', vi: 'học thứ mới', ipa: '' , type: 'cum',unit: 1},
      {en: 'express one ideas', vi: 'thể hiện ý tưởng của mình', ipa: '' , type: 'cum',unit: 1},
      {en: 'make friends with someone', vi: 'làm bạn với ai đó', ipa: '' , type: 'cum',unit: 1},
      {en: 'learn a new language', vi: 'học một ngôn ngữ mới', ipa: '' , type: 'cum',unit: 1},
      {en: 'start university', vi: 'vào đại học', ipa: '' , type: 'cum',unit: 2},
      {en: 'finish university', vi: 'xong đại học', ipa: '' , type: 'cum',unit: 2},
      {en: 'pass with flying colour', vi: 'đạt điểm cao trong kì thi', ipa: '' , type: 'cum',unit: 2},
      {en: 'take an exam', vi: 'làm bài kiểm tra', ipa: '' , type: 'cum',unit: 2},
      {en: 'pass an exam', vi: 'qua bài kiểm tra', ipa: '' , type: 'cum',unit: 2},
      {en: 'cram for', vi: 'học gạo để chuẩn bị cho', ipa: '' , type: 'cum',unit: 2},
      {en: 'enroll', vi: 'nhập học', ipa: ' /ɪnˈroʊl/' , type: 'v',unit: 2},
      {en: 'announce', vi: 'thông báo', ipa: '/əˈnaʊns/ ' , type: 'v',unit: 2},
      {en: 'kindergarten', vi: 'mẫu giáo', ipa: '/ˈkɪn.dəˌɡɑː.tən/' , type: 'n',unit: 2},
      {en: 'assignment', vi: 'bài tập', ipa: '/əˈsaɪn.mənt/' , type: 'n',unit: 2},
      {en: 'curriculum', vi: 'chương trình giảng dạy', ipa: '/kəˈrɪk.jə.ləm/' , type: 'n',unit: 2},
      {en: 'engineering', vi: 'nghành kỹ sư', ipa: '/ˌen.dʒɪˈnɪə.rɪŋ/' , type: 'n',unit: 2},
      {en: 'primary', vi: 'tiểu học', ipa: '/ˈpraɪ.mər.i/' , type: 'n',unit: 2},
      {en: 'uniform', vi: 'đồng phục', ipa: '/ˈjuː.nɪ.fɔːm/' , type: 'n',unit: 2},
      {en: 'revise', vi: 'ôn tập', ipa: '/rɪˈvaɪz/' , type: 'v',unit: 2},
      {en: 'art', vi: 'nghệ thuật', ipa: ' /ɑːt/' , type: 'n',unit: 2},
      {en: 'absent', vi: 'vắng mặt', ipa: 'ˈæb.sənt/' , type: 'adj',unit: 2},
      {en: 'popular', vi: 'thịnh hành', ipa: '/ˈpɒp.jə.lər/' , type: 'adj',unit: 2},
      {en: 'science', vi: 'khoa học', ipa: '/ˈsaɪ.əns/' , type: 'n',unit: 2},
      {en: 'subject', vi: 'môn học', ipa: '/ˈsʌb.dʒekt/' , type: 'n',unit: 2},
      {en: 'secondary', vi: 'cấp 2', ipa: '/ˈsek.ən.dri/' , type: 'adj',unit: 2},
      {en: 'mathematics', vi: 'toán học', ipa: '/ˌmæθˈmæt.ɪks/' , type: 'n',unit: 2},
      {en: 'succeed', vi: 'thành công', ipa: '/səkˈsiːd/' , type: 'v',unit: 2},
      {en: 'nervous', vi: 'lo lắng', ipa: '/ˈnɜː.vəs/' , type: 'adj',unit: 2},
      {en: 'continue', vi: 'tiếp tục', ipa: '/kənˈtɪn.juː/' , type: 'v',unit: 2},
      {en: 'dropout', vi: 'người bỏ học', ipa: '/ˈdrɑːp.aʊt/' , type: 'n',unit: 2},
      {en: 'grade', vi: 'điểm số', ipa: '/ɡreɪd/' , type: 'n',unit: 2},
      {en: 'attend', vi: 'tham gia', ipa: '/əˈtend/' , type: 'v',unit: 2},
      {en: 'term', vi: 'học kì', ipa: '/tɜːm/' , type: 'n',unit: 2},
      {en: 'memorise', vi: 'học thuộc', ipa: '/ˈmem.ə.raɪz/' , type: 'v',unit: 3},
      {en: 'live a quiet life', vi: 'sống cuộc sống bình yên', ipa: '' , type: 'cum',unit: 3},
      {en: 'healthy interest', vi: 'sở thích lành mạnh', ipa: '' , type: 'cum',unit: 3},
      {en: 'spell one name', vi: 'đánh vần tên ai đó', ipa: '' , type: 'cum',unit: 3},
      {en: 'first name', vi: 'tên riêng', ipa: '' , type: 'cum',unit: 3},
      {en: 'grow up', vi: 'lớn lên', ipa: '' , type: 'cum',unit: 3},
      {en: 'beautiful', vi: 'đẹp', ipa: '/ˈbjuː.tɪ.fəl/' , type: 'adj',unit: 3},
      {en: 'favourite', vi: 'ưa thích', ipa: '/ˈfeɪ.vər.ɪt/' , type: 'adv',unit: 3},
      {en: 'crowded', vi: 'đông đúc', ipa: '/ˈkraʊ.dɪd/' , type: 'adj',unit: 3},
      {en: 'peaceful', vi: 'bình yên', ipa: '/ˈpiːs.fəl/' , type: 'adj',unit: 3},
      {en: 'centre', vi: 'trung tâm', ipa: '/ˈsen.tər/' , type: 'n',unit: 3},
      {en: 'north', vi: 'phía Bắc', ipa: ' /nɔːθ/' , type: 'n',unit: 3},
      {en: 'address', vi: 'địa chỉ', ipa: '/əˈdres/' , type: 'n',unit: 3},
      {en: 'call', vi: 'gọi', ipa: '/kɔːl/' , type: 'v',unit: 3},
      {en: 'common', vi: 'phổ biến', ipa: '/ˈkɒm.ən/' , type: 'adj',unit: 3},
      {en: 'south', vi: 'phía Nam', ipa: '/saʊθ/' , type: 'n',unit: 3},
      {en: 'town', vi: 'thị trấn', ipa: '/taʊn/' , type: 'n',unit: 3},
      {en: 'distance', vi: 'khoảng cách', ipa: '/ˈdɪs.təns/' , type: 'n',unit: 3},
      {en: 'live', vi: 'sống', ipa: '/lɪv/' , type: 'v',unit: 3},
      {en: 'meaning', vi: 'ý nghĩa', ipa: '/ˈmiː.nɪŋ/' , type: 'n',unit: 3},
      {en: 'spell', vi: 'đánh vần', ipa: '/spel/' , type: 'v',unit: 3},
      {en: 'contact', vi: 'sự liên lạc', ipa: '/ˈkɒn.tækt/' , type: 'n',unit: 3},
      {en: 'hometown', vi: 'quê hương', ipa: '/ˈhəʊm.taʊn/' , type: 'n',unit: 3},
      {en: 'sign', vi: 'ký tên', ipa: '/saɪn/' , type: 'v',unit: 3},
      {en: 'surname', vi: 'họ', ipa: '/ˈsɜː.neɪm/' , type: 'n',unit: 3},
      {en: 'tell', vi: 'gọi', ipa: '/tel/' , type: 'v',unit: 3},
      {en: 'special', vi: 'đặc biệt', ipa: '/ˈspeʃ.əl/' , type: 'adj',unit: 3},
      {en: 'describe', vi: 'mô tả', ipa: '/dɪˈskraɪb/' , type: 'v',unit: 3},
      {en: 'nickname', vi: 'biệt danh', ipa: '/ˈnɪk.neɪm/' , type: 'n',unit: 3},
      {en: 'know', vi: 'biết', ipa: '/nəʊ/' , type: 'v',unit: 3},
      {en: 'work to tight deadlines', vi: 'làm việc với hạn chót gấp rút', ipa: '' , type: 'cum',unit: 4},
      {en: 'paid-well job', vi: 'việc làm lương cao', ipa: '' , type: 'cum',unit: 4},
      {en: 'be responsible for', vi: 'có trách nhiệm với ', ipa: '' , type: 'cum',unit: 4},
      {en: 'dead-end job', vi: 'công việc không có cơ hội thăng tiến', ipa: '' , type: 'cum',unit: 4},
      {en: 'show up for work', vi: 'có mặt tại chỗ làm', ipa: '' , type: 'cum',unit: 4},
      {en: 'work long hours', vi: 'làm việc ca dài', ipa: '' , type: 'cum',unit: 4},
      {en: 'manager', vi: 'người quản lý', ipa: '/ˈmæn.ɪ.dʒər/' , type: 'n',unit: 4},
      {en: 'challenging', vi: 'tính thách thức', ipa: '/ˈtʃæl.ɪn.dʒɪŋ/' , type: 'adj',unit: 4},
      {en: 'salesperson', vi: 'người bán hàng', ipa: '/ˈseɪlzˌpɜː.sən/' , type: 'n',unit: 4},
      {en: 'pilot', vi: 'phi công', ipa: '/ˈpaɪ.lət/' , type: 'n',unit: 4},
      {en: 'form', vi: 'mẫu đơn', ipa: '/fɔːm/' , type: 'v',unit: 4},
      {en: 'acceptable', vi: 'chấp nhận được', ipa: '/əkˈsept.ə.bəl/' , type: 'adj',unit: 4},
      {en: 'accountant', vi: 'kế toán', ipa: '/əˈkaʊn.tənt/' , type: 'n',unit: 4},
      {en: 'journalist', vi: 'nhà báo', ipa: '/ˈdʒɜː.nə.lɪst/' , type: 'n',unit: 4},
      {en: 'open', vi: 'mở', ipa: '/ˈəʊ.pən/' , type: 'adj',unit: 4},
      {en: 'employer', vi: 'nhà tuyển dụng', ipa: '/ɪmˈplɔɪ.ər/' , type: 'n',unit: 4},
      {en: 'offer', vi: 'đề xuất', ipa: '/ˈɒf.ər/' , type: 'v',unit: 4},
      {en: 'receptionist', vi: 'lễ tân', ipa: '/rɪˈsep.ʃən.ɪst/' , type: 'n',unit: 4},
      {en: 'employee', vi: 'nhân viên', ipa: '/ɪmˈplɔɪ.iː/' , type: 'n',unit: 4},
      {en: 'company', vi: 'công ty', ipa: '/ˈkʌm.pə.ni/' , type: 'n',unit: 4},
      {en: 'design', vi: 'thiết kế', ipa: '/dɪˈzaɪn/' , type: 'v',unit: 4},
      {en: 'cook', vi: 'người đầu bếp', ipa: '/kʊk/' , type: 'n',unit: 4},
      {en: 'assistant', vi: 'trợ lý', ipa: '/əˈsɪs.tənt/' , type: 'n',unit: 4},
      {en: 'engineer', vi: 'kỹ sư', ipa: '/ˌen.dʒɪˈnɪər/' , type: 'n',unit: 4},
      {en: 'hairdresser', vi: 'thợ cắt tóc', ipa: '/ˈheəˌdres.ər/' , type: 'n',unit: 4},
      {en: 'housewife', vi: 'nội trợ', ipa: '/ˈhaʊs.waɪf/' , type: 'n',unit: 4},
      {en: 'lawyer', vi: 'luật sư', ipa: '/ˈlɔɪ.ər/' , type: 'n',unit: 4},
      {en: 'punctual', vi: 'đúng giờ', ipa: '/ˈpʌŋk.tʃu.əl/' , type: 'adj',unit: 4},
      {en: 'architect', vi: 'kiến trúc sư', ipa: '/ˈɑː.kɪ.tekt/' , type: 'n',unit: 4},
      {en: 'owner', vi: 'người chủ', ipa: '/ˈəʊ.nər/' , type: 'n',unit: 4},
      {en: 'file', vi: 'cặp đựng tài liệu', ipa: '/faɪl/' , type: 'n',unit: 5},
      {en: 'arrange', vi: 'sắp xếp', ipa: '/əˈreɪndʒ/' , type: 'v',unit: 5},
      {en: 'jobless', vi: 'thất nghiệp', ipa: '/ˈdʒɒb.ləs/' , type: 'adj',unit: 5},
      {en: 'designer', vi: 'nhà thiết kế', ipa: '/dɪˈzaɪ.nər/' , type: 'n',unit: 5},
      {en: 'filmmaker', vi: 'nhà làm phim', ipa: '/ˈfɪlmˌmeɪ.kər/' , type: 'n',unit: 5},
      {en: 'prepare', vi: 'chuẩn bị', ipa: ' /prɪˈpeər/' , type: 'v',unit: 5},
      {en: 'freelancer', vi: 'người làm việc tự do', ipa: '/ˈfriː.lɑːn.sər/' , type: 'n',unit: 5},
      {en: 'reporter', vi: 'phóng viên', ipa: '/rɪˈpɔː.tər/' , type: 'n',unit: 5},
      {en: 'expert', vi: 'chuyên gia', ipa: '/ˈek.spɜːt/' , type: 'n',unit: 5},
      {en: 'document', vi: 'tài liệu', ipa: '/ˈdɒk.jə.mənt/' , type: 'n',unit: 5},
      {en: 'contract', vi: 'hợp đồng', ipa: '/ˈkɒn.trækt/' , type: 'n',unit: 5},
      {en: 'bank teller', vi: 'giao dịch viên ngân hàng', ipa: '' , type: 'n',unit: 5},
      {en: 'application', vi: 'đơn xin', ipa: '/ˌæp.lɪˈkeɪ.ʃən/' , type: 'n',unit: 5},
      {en: 'nurse', vi: 'y tá', ipa: '/nɜːs/' , type: 'n',unit: 5},
      {en: 'customer', vi: 'khách hàng', ipa: '/ˈkʌs.tə.mər/' , type: 'n',unit: 5},
      {en: 'builder', vi: 'thợ xây', ipa: '/ˈbɪl.dər/' , type: 'n',unit: 5},
      {en: 'qualified', vi: 'đủ khả năng', ipa: 'ˈkwɒl.ɪ.faɪd/' , type: 'n',unit: 5},
      {en: 'photographer', vi: 'thợ chụp ảnh', ipa: '/fəˈtɒɡ.rə.fər/' , type: 'n',unit: 5},
      {en: 'career', vi: 'nghề nghiệp', ipa: '/kəˈrɪər/' , type: 'n',unit: 5},
      {en: 'interview', vi: 'phỏng vấn', ipa: '/ˈɪn.tə.vjuː/' , type: 'n',unit: 5},
      {en: 'secretary', vi: 'thư ký', ipa: '/ˈsek.rə.tər.i/' , type: 'n',unit: 5},
      {en: 'tool', vi: 'công cụ', ipa: '/tuːl/' , type: 'n',unit: 5},
      {en: 'get a job', vi: 'có công việc làm', ipa: '' , type: 'n',unit: 5},
      {en: 'musician', vi: 'nhạc sĩ', ipa: '/mjuːˈzɪʃ.ən/' , type: 'n',unit: 5},
      {en: 'in big trouble', vi: 'gặp rắc rối to', ipa: '' , type: 'cum',unit: 6},
      {en: 'be paid on time', vi: 'trả đúng hạn', ipa: '' , type: 'cum',unit: 6},
      {en: 'run out of money', vi: 'hết tiền', ipa: '' , type: 'cum',unit: 6},
      {en: 'run short of money', vi: 'thiếu tiền', ipa: '' , type: 'cum',unit: 6},
      {en: 'pay rent and bill', vi: 'trả tiền thuê nhà và hóa đơn', ipa: '' , type: 'cum',unit: 6},
      {en: 'cost of living', vi: 'chi phí sinh hoạt', ipa: '' , type: 'cum',unit: 6},
      {en: 'rent', vi: 'tiền thuê nhà', ipa: '/rent' , type: 'n',unit: 6},
      {en: 'rich', vi: 'giàu', ipa: ' /rɪtʃ/' , type: 'adj',unit: 6},
      {en: 'decrease', vi: 'giảm', ipa: '/dɪˈkriːs/' , type: 'v',unit: 6},
      {en: 'price', vi: 'giá tiền', ipa: '/praɪs/' , type: 'n',unit: 6},
      {en: 'lend', vi: 'cho vay', ipa: '/lend/' , type: 'v',unit: 6},
      {en: 'expensive', vi: 'đắt', ipa: '/ɪkˈspen.sɪv/' , type: 'cum',unit: 6},
      {en: 'cost', vi: 'chi phí', ipa: ' /kɔːst/' , type: 'n',unit: 6},
      {en: 'spend', vi: 'chi tiêu', ipa: '/spend/' , type: 'v',unit: 6},
      {en: 'reasonable', vi: 'phải chăng', ipa: '/ˈriː.zən.ə.bəl/' , type: 'adj',unit: 6},
      {en: 'due', vi: 'hạn', ipa: '/djuː/' , type: 'cum',unit: 6},
      {en: 'manage', vi: 'quản lý', ipa: '/ˈmænɪdʒ/' , type: 'v',unit: 6},
      {en: 'broke', vi: 'cháy túi', ipa: ' /brəʊk/' , type: 'adj',unit: 6},
      {en: 'fee', vi: 'lệ phí', ipa: ' /fi:/' , type: 'n',unit: 6},
      {en: 'luxury', vi: 'xa hoa', ipa: '/ˈlʌkʃəri/' , type: 'n',unit: 6},
      {en: 'generous', vi: 'hào phóng', ipa: '/ˈdʒenərəs/' , type: 'adj',unit: 6},
      {en: 'owe', vi: 'nợ', ipa: '/əʊ/' , type: 'adj',unit: 6},
      {en: 'save', vi: 'tiết kiệm', ipa: '/seɪv/' , type: 'v',unit: 6},
      {en: 'bill', vi: 'hóa đơn', ipa: '/bɪl/' , type: 'n',unit: 6},
      {en: 'cheap', vi: 'rẻ', ipa: '/tʃiːp/' , type: 'adj',unit: 6},
      {en: 'note', vi: 'tờ tiền', ipa: '/nəʊt/' , type: 'n',unit: 6},
      {en: 'borrow', vi: 'mượn', ipa: '/ˈbɒrəʊ/' , type: 'v',unit: 6},
      {en: 'raise', vi: 'tăng', ipa: '/reɪz/' , type: 'v',unit: 6},
      {en: 'wasteful', vi: 'phí phạm', ipa: '/ˈweɪstfl/' , type: 'adj',unit: 6},
      {en: 'metro system', vi: 'hệ thống tàu ngầm', ipa: '' , type: 'cum',unit: 7,ex:''},
      {en: 'entertaiment options', vi: 'lựa chọn giải trí', ipa: '' , type: 'cum',unit: 7,ex:''},
      {en: 'put up with', vi: 'chịu đựng', ipa: '' , type: 'cum',unit: 7,ex:''},
      {en: 'quality of life', vi: 'chất lượng cuộc sống', ipa: '' , type: 'cum',unit: 7,ex:''},
      {en: 'pace of life', vi: 'nhịp sống', ipa: '' , type: 'cum',unit: 7,ex:''},
      {en: 'get used to', vi: 'quen dần với việc gì', ipa: '' , type: 'cum',unit: 7,ex:''},
      {en: 'atmosphere', vi: 'bầu không khí', ipa: '/ˈætməsfɪə(r)/' , type: 'n',unit: 7,ex:''},
      {en: 'convenient', vi: 'tiện lợi', ipa: '/kənˈviːniənt/' , type: 'adj',unit: 7,ex:''},
      {en: 'capital', vi: 'thủ đồ', ipa: '/ˈkæpɪtl/' , type: 'n',unit: 7,ex:''},
      {en: 'nightlife', vi: 'cuộc sống về đêm', ipa: '/ˈnaɪtlaɪf/' , type: 'n',unit: 7,ex:''},
      {en: 'service', vi: 'dịch vụ', ipa: '/ˈsɜːvɪs/' , type: 'n',unit: 7,ex:''},
      {en: 'modern', vi: 'hiện đại', ipa: '/ˈmɒdn/' , type: 'adj',unit: 7,ex:''},
      {en: 'quality', vi: 'chất lượng', ipa: '/ˈkwɒləti/' , type: 'n',unit: 7,ex:''},
      {en: 'pavement', vi: 'vỉa hè', ipa: '/ˈpeɪvmənt/' , type: 'n',unit: 7,ex:''},
      {en: 'various', vi: 'đa dạng', ipa: '/ˈveəriəs/' , type: 'adj',unit: 7,ex:''},
      {en: 'exciting', vi: 'sự thích thú', ipa: '/ɪkˈsaɪ.tɪŋ/' , type: 'n',unit: 7,ex:''},
      {en: 'appealing', vi: 'thu hút', ipa: '/əˈpiː.lɪŋ/' , type: 'adj',unit: 7,ex:''},
      {en: 'square', vi: 'quảng trường', ipa: '/skweər/' , type: 'n',unit: 7,ex:''},
      {en: 'opportunity', vi: 'cơ hội', ipa: '/ˈneɪ.bə.hʊd' , type: 'n',unit: 7,ex:'', ex: "Everyone will have an opportunity to comment."},
      {en: 'skyscraper', vi: 'tòa nhà chọc trời', ipa: '/ˈskaɪˌskreɪ.pər/' , type: 'n',unit: 7,ex:'', ex: "The restaurant is at the top of one of the big downtown skyscrapers."},
      {en: 'system', vi: 'hệ thống', ipa: '/ˈsɪs.təm/' , type: 'n',unit: 7,ex:'', ex: 'The legal system operates very differently in the US and Britain.'},
      {en: 'alley', vi: 'ngõ', ipa: '/ˈæl.i/' , type: 'n',unit: 7,ex:'She walked quickly down the alley.'},
      {en: 'central', vi: 'ở giữa', ipa: '/ˈsen.trəl/' , type: 'adj',unit: 7,ex:'Some late news has just come in - a bomb has exploded in central London.'},
      {en: 'district', vi: 'quận', ipa: '/ˈdɪs.trɪkt/' , type: 'n',unit: 7,ex:'The theater district in New York is in midtown Manhattan.'},
      {en: 'lively', vi: 'náo nhiệt', ipa: '/ˈlaɪv.li/' , type: 'adj',unit: 7,ex:"It's hard work teaching a class of lively children."},
      {en: 'tower', vi: 'tòa tháp', ipa: '/taʊər/' , type: 'n',unit: 7,ex:'He works in an office tower in downtown San Francisco.'},
      {en: 'nightclub', vi: 'hộp đêm', ipa: '/ˈnaɪt.klʌb/' , type: 'n',unit: 7,ex:'Plans to build a new nightclub in the neighbourhood have enraged local residents.'},
      {en: 'tire one out', vi: 'khiến ai đó mệt lử', ipa: '' , type: 'cum',unit: 7,ex:''},
      {en: 'air quality', vi: 'chất lượng không khí', ipa: '' , type: 'cum',unit: 7,ex:''},
      {en: 'traffic jam', vi: 'tắt đường', ipa: '' , type: 'cum',unit: 7,ex:''},
      {en: 'drive recklessly', vi: 'lái xe ẩu', ipa: '/ˈrek.ləs.li/' , type: 'cum',unit: 7,ex:'He was charged with speeding and driving recklessly.'},
      {en: 'drive one insane', vi: 'Khiến ai đó phát điên', ipa: '' , type: 'cum',unit: 7,ex:'drive the neighbourhood insane'},
      {en: 'traffic noise', vi: 'tiếng ồn giao thông', ipa: '' , type: 'cum',unit: 7,ex:''},
      {en: 'pricey', vi: 'đắt đỏ', ipa: '/ˈpraɪ.si/' , type: 'adj',unit: 8,ex:''},
      {en: 'pickpocket', vi: 'kẻ móc túi', ipa: '/ˈpɪkˌpɒk.ɪt/' , type: 'n',unit: 8,ex:''},
      {en: 'selfish', vi: 'ích kỉ', ipa: 'ˈsel.fɪʃ/' , type: 'adj',unit: 8,ex:''},
      {en: 'affordable', vi: 'vừa túi tiền', ipa: '/əˈfɔː.də.bəl/' , type: 'adj',unit: 8,ex:''},
      {en: 'throw', vi: 'ném', ipa: '/θrəʊ/' , type: 'v',unit: 8,ex:''},
      {en: 'poor', vi: 'nghèo', ipa: '/pɔːr/' , type: 'adj',unit: 8,ex:''},
      {en: 'beggar', vi: 'người ăn xin', ipa: '/ˈbeɡ.ər/' , type: 'n',unit: 8,ex:''},
      {en: 'population', vi: 'dân số', ipa: '/ˌpɒp.jəˈleɪ.ʃən/' , type: 'n',unit: 8,ex:''},
      {en: 'demand', vi: 'nhu cầu', ipa: '/dɪˈmɑːnd/' , type: 'v',unit: 8,ex:''},
      {en: 'lack', vi: 'thiếu', ipa: '/læk/' , type: 'n',unit: 8,ex:'Her only problem is a lack of confidence.'},
      {en: 'build', vi: 'xây', ipa: ' /bɪld/' , type: 'v',unit: 8,ex:"They're building new houses by the river."},
      {en: 'room', vi: 'chỗ trống', ipa: '/ruːm/' , type: 'n',unit: 8,ex:''},
      {en: 'vehicle', vi: 'phương tiện giao thông', ipa: '/ˈvɪə.kəl/' , type: 'n',unit: 8,ex:'Road vehicles include cars, buses, and trucks.'},
      {en: 'bridge', vi: 'cây cầu', ipa: '/brɪdʒ/' , type: 'n',unit: 8,ex:'The island is joined to the mainland by a road bridge.'},
      {en: 'daily', vi: 'hằng ngày', ipa: '/ˈdeɪ.li/' , type: 'adv',unit: 8,ex:''},
      {en: 'rubbish', vi: 'rác', ipa: '/ˈrʌb.ɪʃ/' , type: 'n',unit: 8,ex:'I forgot to put the rubbish out this morning.'},
      {en: 'facility', vi: 'cơ sở', ipa: '/fəˈsɪl.ə.ti/' , type: 'n',unit: 8,ex:"New vehicles are inspected at the company's inspection facility."},
      {en: 'unhealthy', vi: 'không lành mạnh', ipa: '/ʌnˈhel.θi/' , type: 'adj',unit: 8,ex:'We worked very hard under unhealthy and harsh conditions and without any support from outside.'},
      {en: 'overpopulated', vi: 'vượt dân số', ipa: '/ˌəʊ.vəˈpɒp.jə.leɪ.tɪd/' , type: 'adj',unit: 8,ex:'In the 1890s, people were deserting the countryside for overpopulated cities.'},
      {en: 'accommodation', vi: 'chổ ở', ipa: '/əˌkɒm.əˈdeɪ.ʃən/' , type: 'n',unit: 8,ex:'They paid for his flights and hotel accommodations.'},
      {en: 'crime', vi: 'tội', ipa: ' /kraɪm/' , type: 'n',unit: 8,ex:'He has admitted committing several crimes, including fraud.'},
      {en: 'security', vi: 'an ninh', ipa: '/sɪˈkjʊə.rə.ti' , type: 'n',unit: 8,ex:'The station was closed for two hours because of a security alert.'},
      {en: 'pollution', vi: 'sự ô nhiễm', ipa: '/pəˈluː.ʃən/' , type: 'n',unit: 8,ex:'The company claims it is not responsible for the pollution in the river.'},
      {en: 'scam', vi: 'vụ lừa tiền', ipa: '/skæm' , type: 'n',unit: 8,ex:'She was involved in an insurance scam, collecting on false accident claims.'},
      {en: 'move into a flat', vi: 'chuyển vào một căn hộ', ipa: 'd' , type: 'cum',unit: 9,ex:''},
      {en: 'be fully furnished', vi: 'có đầy đủ đồ đạt', ipa: 'd' , type: 'cum',unit: 9,ex:''},
      {en: 'the view from', vi: 'khung cảnh nhìn từ', ipa: 'd' , type: 'cum',unit: 9,ex:''},
      {en: 'a housewarming party', vi: 'bữa tiệc tân gia', ipa: 'd' , type: 'cum',unit: 9,ex:''},
      {en: 'be within walking distance of', vi: 'đủ gần để đi bộ đến đâu đó', ipa: 'd' , type: 'cum',unit: 9,ex:''},
      {en: 'modern conveniences', vi: 'các tiện nghi hiện đại', ipa: 'd' , type: 'cum',unit: 9,ex:''},
      {en: 'away', vi: 'cách xa', ipa: '/əˈweɪ/' , type: 'adv',unit: 9,ex:'Ms Watson is away on holiday until the end of the week.'},
      {en: 'furniture', vi: 'nội thất', ipa: '/ˈfɜː.nɪ.tʃər/' , type: 'n',unit: 9,ex:'We placed the order for the furniture six weeks ago.'},
      {en: 'comfortable', vi: 'thỏa mái', ipa: '/ˈkʌm.fə.tə.bəl/' , type: 'adj',unit: 9,ex:"I don't feel comfortable in high heels."},
      {en: 'carpet', vi: 'thảm lót sàn', ipa: '/ˈkɑː.pɪt/' , type: 'n',unit: 9,ex:'He was busy hoovering the bedroom carpet when I got home.'},
      {en: 'curtain', vi: 'rèm cửa', ipa: '/ˈkɜː.tən' , type: 'adv',unit: 9,ex:'Heavy curtains blocked out the sunlight.'},
      {en: 'housemate', vi: 'bạn cùng nhà', ipa: '/ˈhaʊs.meɪt/' , type: 'n',unit: 9,ex:''},
      {en: 'flat', vi: 'căn hộ', ipa: '/flæt/' , type: 'n',unit: 9,ex:'She borrowed a garden roller to roll the grass flat.'},
      {en: 'air conditioner', vi: 'máy điều hòa', ipa: ' /ˈeə kənˌdɪʃ.ən.ər/' , type: 'n',unit: 9,ex:'The room temperature was controlled by using an air conditioner.'},
      {en: 'rug', vi: 'tấm thảm', ipa: '/rʌɡ/' , type: 'n',unit: 9,ex:'My dog loves lying on the rug in front of the fire.'},
      {en: 'light', vi: 'ánh sáng', ipa: '/laɪt/' , type: 'n',unit: 9,ex:'She could see the city lights in the distance.'},
      {en: 'antique', vi: 'đồ cổ', ipa: '/ænˈtiːk/' , type: 'n',unit: 9,ex:'These kids make me feel like an antique.'},
      {en: 'fully', vi: 'hoàn toàn', ipa: '/ˈfʊl.i/' , type: 'adv',unit: 9,ex:'I fully intended to call you last night.'},
      {en: 'cramped', vi: 'chật chội', ipa: '/kræmpt' , type: 'adv',unit: 9,ex:'He managed to get a bed in a cramped student apartment.'},
      {en: 'decorate', vi: 'trang trí', ipa: '/ˈdek.ə.reɪt/' , type: 'v',unit: 9,ex:"We're going to decorate the kitchen next week."},
      {en: 'building', vi: 'tòa nhà', ipa: '/ˈbɪl.dɪŋ/' , type: 'n',unit: 9,ex:'The art department and the main college are in two separate buildingss'},
      {en: 'beautifully', vi: 'một cách đẹp đẽ', ipa: '/ˈbjuː.tɪ.fəl.i/ ' , type: 'adv',unit: 9,ex:'Their house is beautifully decorated.'},
      {en: 'place', vi: 'nơi', ipa: '/pleɪs/' , type: 'n',unit: 9,ex:'Her garden was a cool pleasant place to sit.'},
      {en: 'balcony', vi: 'ban công', ipa: ' /ˈbæl.kə.ni/' , type: 'n',unit: 9,ex:'We had a drink on the hotel balcony.'},
      {en: 'drive', vi: 'chuyến xe', ipa: '/draɪv/' , type: 'v',unit: 9,ex:"They're driving to Chicago on Tuesday."},
      {en: 'bookshelf', vi: 'giá sách', ipa: '/ˈbʊk.ʃelf/' , type: 'n',unit: 9,ex:'The entire series ought to find a place on every country house bookshelf.'},
      {en: 'share', vi: 'chia sẻ', ipa: '/ʃeər/' , type: 'v',unit: 9,ex:'We share an interest in sailing.'},
      {en: 'roommate', vi: 'bạn cùng phòng', ipa: '/ˈruːm.meɪt/' , type: 'n',unit: 9,ex:'Jean was my roommate during our first year at college.'},
      {en: 'view', vi: 'khung cảnh', ipa: '/vjuː/' , type: 'adv',unit: 9,ex:'Everyone will have a chance to make their views known at the meeting.'},
      {en: 'face', vi: 'phương hướng', ipa: '/feɪs/' , type: 'v',unit: 9,ex:'This house faces south'},
      {en: 'be based in area', vi: 'sống ở một khu vực', ipa: '' , type: 'cum',unit: 10,ex:''},
      {en: 'convenience store', vi: 'cửa hàng tiện lợi', ipa: '' , type: 'cum',unit: 10,ex:''},
      {en: 'construction site', vi: 'công trường xây dựng', ipa: '' , type: 'cum',unit: 10,ex:''},
      {en: 'grocery store', vi: 'cửa hàng tạp hóa', ipa: '/ˈɡrəʊ.sər.i' , type: 'cum',unit: 10,ex:''},
      {en: 'shopping mall', vi: 'trung tâm thương mại', ipa: '' , type: 'cum',unit: 10,ex:''},
      {en: 'bulletin board', vi: 'bảng tin', ipa: '/ˈbʊl.ə.tɪn bɔːd/' , type: 'cum',unit: 10,ex:'bảng tin ở tổ dân phố'},
      {en: 'noisy', vi: 'ồn ào', ipa: '' , type: 'adv',unit: 10,ex:''},
      {en: 'gym', vi: 'phòng tập thể hình', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 10,ex:''},
      {en: 'property', vi: 'tài sản', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 10,ex:''},
      {en: 'complicated', vi: 'phức tạp', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 10,ex:''},
      {en: 'playground', vi: 'sân chơi', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 10,ex:''},
      {en: 'cosy', vi: 'ấm cúm', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 10,ex:''},
      {en: 'friendly', vi: 'thân thiện', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 10,ex:''},
      {en: 'pool', vi: 'bể bơi', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 10,ex:''},
      {en: 'ground', vi: 'mặt đất', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 10,ex:''},
      {en: 'chilled', vi: 'thư giãn', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 10,ex:''},
      {en: 'clinic', vi: 'phòng khám', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 10,ex:''},
      {en: 'invited', vi: 'mời', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 10,ex:''},
      {en: 'safe', vi: 'an toàn', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 10,ex:''},
      {en: 'block', vi: 'khu nhà', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 10,ex:''},
      {en: 'always', vi: 'luôn luôn', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 10,ex:''},
      {en: 'mostly', vi: 'mặc dù', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 10,ex:''},
      {en: 'one-way', vi: 'một chiều', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 10,ex:''},
      {en: 'vibe', vi: 'bầu không khí', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 10,ex:''},
      {en: 'brivant', vi: 'sối động', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 10,ex:''},
      {en: 'inform', vi: 'báo tin', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 10,ex:''},
      {en: 'develop', vi: 'phát triển', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 10,ex:''},
      {en: 'area', vi: 'khu vực', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 10,ex:''},
      {en: 'everywhere', vi: 'mọi nơi', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 10,ex:''},
      {en: 'comfy', vi: 'thỏa mái', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 10,ex:''},
      {en: 'pack one stuff', vi: 'gói gém đồ đạc của bản thân', ipa: '/ˈneɪ.bə.hʊd' , type: 'cum',unit: 11,ex:''},
      {en: 'in the middle of nowhere', vi: 'nơi khỉ ho cò gáy', ipa: '/ˈneɪ.bə.hʊd' , type: 'cum',unit: 11,ex:''},
      {en: 'escape the city', vi: 'trốn khỏi thành phố', ipa: '/ˈneɪ.bə.hʊd' , type: 'cum',unit: 11,ex:''},
      {en: 'book a flight', vi: 'đặt vé máy bay', ipa: '/ˈneɪ.bə.hʊd' , type: 'cum',unit: 11,ex:''},
      {en: 'hotel reservation', vi: 'dịch vụ đặt phòng khách sạn', ipa: '/ˌrez.əˈveɪ.ʃən/' , type: 'cum',unit: 11,ex:''},
      {en: 'destination', vi: 'điểm đến', ipa: '/ˈneɪ.bə.hʊd' , type: 'cum',unit: 11,ex:''},
      {en: 'experience', vi: 'trải nghiệm', ipa: '/ɪkˈspɪə.ri.əns/' , type: 'v',unit: 11,ex:'We experienced a lot of difficulty in selling our house.'},
      {en: 'excited', vi: 'hứng thú', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 11,ex:''},
      {en: 'flight', vi: 'chuyến bay', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 11,ex:''},
      {en: 'memory', vi: 'kỉ niệm', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 11,ex:''},
      {en: 'disappointed', vi: 'thất vọng', ipa: ' /ˌdɪs.əˈpɔɪn.tɪd/' , type: 'adj',unit: 11,ex:"He was disappointed to find they'd already left."},
      {en: 'stay', vi: 'thời gian ở', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 11,ex:''},
      {en: 'delay', vi: 'sự trì hoãn', ipa: '/ˈneɪ.bə.hʊd' , type: 'n',unit: 11,ex:''},
      {en: 'postcard', vi: 'bưu thiếp', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 11,ex:''},
      {en: 'nowadays', vi: 'ngày nay', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 11,ex:''},
      {en: 'discover', vi: 'khám phá', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 11,ex:''},
      {en: 'journey', vi: 'cuộc hành trình', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 11,ex:''},
      {en: 'book', vi: 'đặt chỗ', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 11,ex:''},
      {en: 'visa', vi: 'thị thực', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 11,ex:''},
      {en: 'moment', vi: 'khoảnh khắc', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 11,ex:''},
      {en: 'reception', vi: 'quầy tiếp tân', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 11,ex:''},
      {en: 'travelling', vi: 'du lịch', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 11,ex:''},
      {en: 'escape', vi: 'trốn khỏi', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 11,ex:''},
      {en: 'amazing', vi: 'đáng kinh ngạc', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 11,ex:''},
      {en: 'adventure', vi: 'cuộc phưu lưu', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 11,ex:''},
      {en: 'huge', vi: 'đồ sộ', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 11,ex:''},
      {en: 'tourist', vi: 'hành khách', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 11,ex:''},
      {en: 'chance', vi: 'cơ hội', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 11,ex:''},
      {en: 'tour', vi: 'chuyến du lịch', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 11,ex:''},
      {en: 'go the sightseeing', vi: 'đi ngắm cảnh', ipa: '/ˈneɪ.bə.hʊd' , type: 'cum',unit: 12,ex:''},
      {en: 'the old quarter', vi: 'Khu phố cổ', ipa: '/ˈneɪ.bə.hʊd' , type: 'cum',unit: 12,ex:''},
      {en: 'go for a walk', vi: 'đi dạo', ipa: '/ˈneɪ.bə.hʊd' , type: 'cum',unit: 12,ex:''},
      {en: 'during one stay in', vi: 'trong thời gian ai ở tại', ipa: '/ˈneɪ.bə.hʊd' , type: 'cum',unit: 12,ex:''},
      {en: 'historical site', vi: 'di tích lịch sử', ipa: '/ˈneɪ.bə.hʊd' , type: 'cum',unit: 12,ex:''},
      {en: 'must-to activites', vi: 'hoạt động không thể bỏ qua', ipa: '/ˈneɪ.bə.hʊd' , type: 'cum',unit: 12,ex:''},
      {en: 'resort', vi: 'khu nghĩ dưỡng', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 12,ex:''},
      {en: 'mausoleum', vi: 'lăng tẩm', ipa: '/ˌmɔː.zəˈliː.əm/' , type: 'n',unit: 12,ex:'I have no desire to introduce into this mausoleum of calm any air or breath of controversy.'},
      {en: 'touristy', vi: 'đông du khách', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 12,ex:''},
      {en: 'taste', vi: 'nếm vị', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 12,ex:''},
      {en: 'history', vi: 'lịch sử', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 12,ex:''},
      {en: 'campsite', vi: 'bãi cắm trại', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 12,ex:''},
      {en: 'guide', vi: 'hướng dẫn viên', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 12,ex:''},
      {en: 'sightseeing', vi: 'ngắm cảnh', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 12,ex:''},
      {en: 'try', vi: 'cố gắng', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 12,ex:''},
      {en: 'hike', vi: 'đi bộ đường dài', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 12,ex:''},
      {en: 'local', vi: 'địa phương', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 12,ex:''},
      {en: 'temple', vi: 'đền', ipa: 'tem.pəl/' , type: 'adv',unit: 12,ex:'On a clear day you can see the temple in the distance.'},
      {en: 'pagoda', vi: 'chùa', ipa: '/pəˈɡəʊ.də/' , type: 'n',unit: 12,ex:''},
      {en: 'option', vi: 'lựa chọn', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 12,ex:''},
      {en: 'homestay', vi: 'nhà nghỉ của dân', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 12,ex:''},
      {en: 'church', vi: 'nhà thờ', ipa: '/tʃɜːtʃ/' , type: 'n',unit: 12,ex:'The town has four churches.'},
      {en: 'hidden', vi: 'bị ẩn dấu', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 12,ex:''},
      {en: 'recommend', vi: 'đề xuất', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 12,ex:''},
      {en: 'lovely', vi: 'đáng yêu', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 12,ex:''},
      {en: 'market', vi: 'chợ', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 12,ex:''},
      {en: 'lover', vi: 'tình nhân', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 12,ex:''},
      {en: 'route', vi: 'tuyến đường', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 12,ex:''},
      {en: 'leisure', vi: 'thời gian rảnh', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 12,ex:''},
      {en: 'war', vi: 'chiến tranh', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 12,ex:''},
      {en: 'priest', vi: 'linh mục', ipa: '/ˈneɪ.bə.hʊd' , type: 'n',unit: 13,ex:''},
      {en: 'generally', vi: 'nhìn chung thì', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 13,ex:''},
      {en: 'celebration', vi: 'ăn mừng', ipa: '/ˈneɪ.bə.hʊd' , type: 'n',unit: 13,ex:''},
      {en: 'occasion', vi: 'dịp đặt biệt', ipa: '/ˈneɪ.bə.hʊd' , type: 'adv',unit: 13,ex:''},
      {en: 'relative', vi: 'họ hàng', ipa: '/ˈneɪ.bə.hʊd' , type: 'n',unit: 13,ex:''},
      {en: 'guest', vi: 'khách', ipa: '/ˈneɪ.bə.hʊd' , type: 'n',unit: 13,ex:''},
      {en: 'pray', vi: 'cầu nguyện', ipa: '/ˈneɪ.bə.hʊd' , type: 'v',unit: 13,ex:''},
      {en: 'party', vi: 'tiệc tùng', ipa: '/ˈneɪ.bə.hʊd' , type: 'v',unit: 13,ex:''},
      {en: 'wedding', vi: 'lễ cưới', ipa: '/ˈneɪ.bə.hʊd' , type: 'n',unit: 13,ex:''},
      {en: 'festival', vi: 'lễ hội', ipa: '/ˈneɪ.bə.hʊd' , type: 'n',unit: 13,ex:''},
      {en: 'firework', vi: 'pháo hoa', ipa: '/ˈneɪ.bə.hʊd' , type: 'n',unit: 13,ex:''},
      {en: 'ceremony', vi: 'buổi lễ', ipa: '/ˈneɪ.bə.hʊd' , type: 'n',unit: 13,ex:''},
      {en: 'offering', vi: 'lễ vật', ipa: '/ˈneɪ.bə.hʊd' , type: 'n',unit: 13,ex:''},
      {en: 'welcome', vi: 'hoan nghênhh', ipa: '/ˈneɪ.bə.hʊd' , type: 'v',unit: 13,ex:''},
      {en: 'luck', vi: 'vận may', ipa: '/ˈneɪ.bə.hʊd' , type: 'n',unit: 13,ex:''},
      {en: 'tidy', vi: 'dọn dẹp', ipa: '/ˈneɪ.bə.hʊd' , type: 'v',unit: 13,ex:''},
      {en: 'exchange', vi: 'trao đổi', ipa: '/ˈneɪ.bə.hʊd' , type: 'v',unit: 13,ex:''},
      {en: 'public', vi: 'công chúng', ipa: '/ˈneɪ.bə.hʊd' , type: 'n',unit: 13,ex:''},
      {en: 'holiday', vi: 'ngày lễ', ipa: '/ˈneɪ.bə.hʊd' , type: 'n',unit: 13,ex:''},
      {en: 'national', vi: 'toàn quốc', ipa: '/ˈneɪ.bə.hʊd' , type: 'adj',unit: 13,ex:''},
      {en: 'congratulation', vi: 'chúc mừng', ipa: '/ˈneɪ.bə.hʊd' , type: 'n',unit: 13,ex:''},
      {en: 'anniversary', vi: 'ngày kỉ niệm', ipa: '/ˈneɪ.bə.hʊd' , type: 'n',unit: 13,ex:''},
      {en: 'lantern', vi: 'đèn lồng', ipa: '/ˈneɪ.bə.hʊd' , type: 'n',unit: 13,ex:''},
      {en: 'peace', vi: 'sự bình yên', ipa: '/ˈneɪ.bə.hʊd' , type: 'n',unit: 13,ex:''},
      {en: 'throw a party', vi: 'tổ chức một bữa tiệc', ipa: '/ˈneɪ.bə.hʊd' , type: 'cum',unit: 13,ex:''},
      {en: 'pray for good luck', vi: 'cầu vận may', ipa: '/ˈneɪ.bə.hʊd' , type: 'cum',unit: 13,ex:''},
      {en: 'loved ones', vi: 'những người thân yêu', ipa: '/ˈneɪ.bə.hʊd' , type: 'cum',unit: 13,ex:''},
      {en: 'wedding party', vi: 'tiệc cưới', ipa: '/ˈneɪ.bə.hʊd' , type: 'cum',unit: 13,ex:''},
      {en: 'national holiday', vi: 'ngày nghĩ lễ toàn quốc', ipa: '/ˈneɪ.bə.hʊd' , type: 'cum',unit: 13,ex:''},
      {en: 'feel a home', vi: 'cảm giác như ở nhà', ipa: '/ˈneɪ.bə.hʊd' , type: 'cum',unit: 13,ex:''},
      {en: 'brawl', vi: 'cãi lộn, ẩu đã', ipa: '/brɔ:l/', type: 'n',unit: 13,ex:''},
      {en: 'regret', vi: 'sự hối tiếc', ipa: '/riˈgret/' , type: 'n',unit: 13,ex:''},
      {en: 'pillar', vi: 'cột', ipa: '/riˈgret/' , type: 'n',unit: 14,ex:''},
      {en: 'religion', vi: 'tôn giáo', ipa: '/rɪˈlɪdʒ.ən/' , type: 'n',unit: 14,ex:''},
      {en: 'pretend', vi: 'giả vờ', ipa: '/riˈgret/' , type: 'n',unit: 14,ex:''},
      {en: 'control', vi: 'điều khiển', ipa: ' /ʃraɪn/' , type: 'n',unit: 14,ex:''},
      {en: 'marriage', vi: 'hôn nhân', ipa: ' /ʃraɪn/' , type: 'n',unit: 14,ex:''},
      {en: 'difference', vi: 'sự khác biệt', ipa: ' /ʃraɪn/' , type: 'n',unit: 14,ex:''},
      {en: 'angry', vi: 'nóng giận', ipa: ' /ʃraɪn/' , type: 'adj',unit: 14,ex:''},
      {en: 'taboo', vi: 'điều cấm kị', ipa: ' /ʃraɪn/' , type: 'n',unit: 14,ex:''},
      {en: 'taboo', vi: 'điều cấm kị', ipa: ' /ʃraɪn/' , type: 'n',unit: 14,ex:''},
      {en: 'believe', vi: 'tin', ipa: '' , type: 'cum',unit: 14,ex:''},
      {en: 'avoid', vi: 'tránh', ipa: '' , type: 'cum',unit: 14,ex:''},
      {en: 'traditional', vi: 'truyền thống', ipa: '' , type: 'cum',unit: 14,ex:''},
      {en: 'proud', vi: 'tự hào', ipa: '' , type: 'cum',unit: 14,ex:''},
      {en: 'familiar', vi: 'thân thiện', ipa: '/fəˈmɪl.i.jɚ' , type: 'adj',unit: 14,ex:''},
      {en: 'rule', vi: 'quy tắc', ipa: '' , type: 'cum',unit: 14,ex:''},
      {en: 'care', vi: 'sự chú tâm', ipa: '' , type: 'cum',unit: 14,ex:''},
      {en: 'respect', vi: 'tôn trọng', ipa: '' , type: 'cum',unit: 14,ex:''},
      {en: 'expect', vi: 'mong đợi', ipa: '' , type: 'cum',unit: 14,ex:''},
      {en: 'surpire', vi: 'ngạc nhiên', ipa: '' , type: 'cum',unit: 14,ex:''},
      {en: 'mean', vi: 'ý định', ipa: '' , type: 'cum',unit: 14,ex:''},
      {en: 'fair', vi: 'công bằng', ipa: '' , type: 'cum',unit: 14,ex:''},
      {en: 'normal', vi: 'bình thường', ipa: '' , type: 'cum',unit: 14,ex:''},
      {en: 'buddhist', vi: 'phật tử', ipa: '' , type: 'cum',unit: 14,ex:''},
      {en: 'be under pressure to', vi: 'chiuh áp lực phải ( to do something)', ipa: '' , type: 'cum',unit: 14,ex:''},
      {en: 'boost family bonding', vi: 'tăng tính gắn kết trong gia đình', ipa: '' , type: 'cum',unit: 14,ex:''},
      {en: 'cultural difference', vi: 'sự khác biệt văn hóa', ipa: '' , type: 'cum',unit: 14,ex:''},
      {en: 'see a fortune teller', vi: 'đi xem bói', ipa: '' , type: 'cum',unit: 14,ex:''},
      {en: 'tell your fortune', vi: 'xem số mệnh', ipa: '' , type: 'cum',unit: 14,ex:''},
      {en: 'meant to be', vi: 'đã được trời định', ipa: '' , type: 'cum',unit: 14,ex:''},
      {en: 'costumes', vi: 'trang phục, y phục', ipa: '[ɪnˈdʊr]' , type: 'cum',unit: 14,ex:'costume piece'},
      {en: 'beginning', vi: 'sự khởi đầu', ipa: '[ɪnˈdʊr]' , type: 'n',unit: 15,ex:''},
      {en: 'rainy', vi: 'nhiều mưa', ipa: '[ɪnˈdʊr]' , type: 'adj',unit: 15,ex:''},
      {en: 'season', vi: 'mùa', ipa: '[ɪnˈdʊr]' , type: 'n',unit: 15,ex:''},
      {en: 'pleasant', vi: 'dễ chịu', ipa: '[ɪnˈdʊr]' , type: 'cum',unit: 15,ex:''},
      {en: 'middle', vi: 'giữa', ipa: '[ɪnˈdʊr]' , type: 'cum',unit: 15,ex:''},
      {en: 'period', vi: 'khoảng thời gian', ipa: '[ɪnˈdʊr]' , type: 'cum',unit: 15,ex:''},
      {en: 'breeze', vi: 'cơn gió nhẹ', ipa: '[ɪnˈdʊr]' , type: 'cum',unit: 15,ex:''},
      {en: 'climate', vi: 'khí hậu', ipa: '[ɪnˈdʊr]' , type: 'cum',unit: 15,ex:''},
      {en: 'drizzle', vi: 'mưa phùn', ipa: '[ɪnˈdʊr]' , type: 'cum',unit: 15,ex:''},
      {en: 'forcast', vi: 'dự báo', ipa: '[ɪnˈdʊr]' , type: 'cum',unit: 15,ex:''},
      {en: 'temperature', vi: 'nhiệt độ', ipa: '[ɪnˈdʊr]' , type: 'cum',unit: 15,ex:''},
      {en: 'nasty', vi: 'khó chịu', ipa: '[ɪnˈdʊr]' , type: 'cum',unit: 15,ex:''},
      {en: 'rainy', vi: 'mưa nhiều', ipa: '[ɪnˈdʊr]' , type: 'cum',unit: 15,ex:''},
      {en: 'season', vi: 'mùa', ipa: '[ɪnˈdʊr]' , type: 'cum',unit: 15,ex:''},
      {en: 'pleasant', vi: 'thỏa mái', ipa: '[ɪnˈdʊr]' , type: 'cum',unit: 15,ex:''},
      {en: 'beginning', vi: 'khởi đầu', ipa: '[ɪnˈdʊr]' , type: 'cum',unit: 15,ex:''},
      {en: 'typhoon', vi: 'bão nhiệt đới', ipa: '[ɪnˈdʊr]' , type: 'cum',unit: 15,ex:''},
      {en: 'shower', vi: 'mưa rào', ipa: '[ɪnˈdʊr]' , type: 'cum',unit: 15,ex:''},
      {en: 'sunny', vi: 'nhiều nắng', ipa: '[ɪnˈdʊr]' , type: 'cum',unit: 15,ex:''},
      {en: 'end', vi: 'sự kết thúc', ipa: '[ɪnˈdʊr]' , type: 'cum',unit: 15,ex:''},
      {en: 'flood', vi: 'bão', ipa: '[ɪnˈdʊr]' , type: 'cum',unit: 15,ex:''},
      {en: 'last', vi: 'kéo dài', ipa: '[ɪnˈdʊr]' , type: 'cum',unit: 15,ex:''},
      {en: 'humid', vi: 'ẩm', ipa: '[ɪnˈdʊr]' , type: 'cum',unit: 15,ex:''},
      {en: 'awful', vi: 'kinh khủng', ipa: '[ɪnˈdʊr]' , type: 'cum',unit: 15,ex:''},
      {en: 'approach', vi: 'tiếp', ipa: '[ɪnˈdʊr]' , type: 'cum',unit: 15,ex:''},
      {en: 'celsius', vi: 'độ C', ipa: '[ɪnˈdʊr]' , type: 'cum',unit: 15,ex:''},
      {en: 'typical', vi: 'điển hình', ipa: '[ɪnˈdʊr]' , type: 'cum',unit: 15,ex:''},
      {en: 'bear the heat', vi: 'chịu sức nóng', ipa: '[ɪnˈdʊr]' , type: 'cum',unit: 15,ex:''},
      {en: 'rain cats and dogs', vi: 'mưa xối xả', ipa: '[ɪnˈdʊr]' , type: 'cum',unit: 15,ex:''},
      {en: 'weather forecast', vi: 'dư báo thời tiết', ipa: '[ɪnˈdʊr]' , type: 'cum',unit: 15,ex:''},
      {en: 'high wind', vi: 'gió lớn', ipa: '[ɪnˈdʊr]' , type: 'cum',unit: 15,ex:''},
      {en: 'temperature drops', vi: 'nhiệt độ giảm', ipa: '[ɪnˈdʊr]' , type: 'cum',unit: 15,ex:''},
      {en: 'cold spell', vi: 'đợt rét', ipa: '[ɪnˈdʊr]' , type: 'cum',unit: 15,ex:''},
      {hello: 'hi'},
    ]
    return arr;
  }

}
const instance = new StoreFriendList();
export default instance;